CREATE COLUMN TABLE "DBUSER"."ADVISORIES4"(
	"index" INTEGER,
	"pbc_number" INTEGER,
	"topic" NVARCHAR(5000)
)
UNLOAD PRIORITY 5 AUTO MERGE;
ALTER TABLE "DBUSER"."ADVISORIES4" ADD ("topic_embedding" REAL_VECTOR GENERATED ALWAYS AS "VECTOR_EMBEDDING"("topic", 'DOCUMENT', 'SAP_NEB.20240715'));
